---
smallstep_ca_image: docker.io/smallstep/step-ca:latest
smallstep_ca_container_name: smallstep-ca
smallstep_ca_data_dir: /var/lib/smallstep-ca
smallstep_ca_config_dir: /etc/smallstep-ca

# Step-CA configuration
smallstep_ca_name: "Smallstep CA"
smallstep_ca_password: "password" # Should be overridden in production
smallstep_ca_dns_names:
  - localhost

# Systemd configuration
smallstep_ca_service_name: smallstep-ca
smallstep_ca_systemd_dir: /etc/containers/systemd
