---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Get CA fingerprint from host
      ansible.builtin.command: podman exec step-ca step certificate fingerprint /home/step/certs/root_ca.crt
      register: ca_fingerprint
      delegate_to: localhost
      become: false
      changed_when: false

    - name: Set fingerprint fact
      ansible.builtin.set_fact:
        smallstep_cli_ca_fingerprint: "{{ ca_fingerprint.stdout }}"

  roles:
    - role: adborden.smallstep_cli
